[project]
authors = ["menamerai <rphananh@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "toystory"
platforms = ["win-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
opencv = ">=4.11.0,<5"
supabase = ">=2.13.0,<3"

[pypi-dependencies]
fastapi = { version = ">=0.115.8, <0.116", extras = ["standard"] }
mediapipe = ">=0.10.14, <0.11"
deepface = ">=0.0.93, <0.0.94"
